### ISSUE TITLE
load public or private key in BASE64 format does not work

### ISSUE THREAD

**Issue by ggaborg** [verhas/License3jRepl#3]
in `App.java` `loadPrivateKey()` and `loadPublicKey()` methods should use `BASE_64` constant instead of `TEXT` at this line:
```
final var format = IOFormat.valueOf(env.parser().getOrDefault(FORMAT, BINARY, Set.of(TEXT, BINARY)));
```

**Comment by verhas** [comment]
I will have a look at it. If you feel like, you can create the change and a pull request.

**Comment by ggaborg** [comment]
i would need rights to create a branch

**Comment by verhas** [comment]
No, you do not. You can create a pull request to any repository on GitHub..

Create a fork. This is a copy of the original repo under your organization. Make branch (optional, you can use your own master for the purpose) and create a pull request from your fork to the original repo your forked from.
