### ISSUE TITLE
Is there a way to automate the REPL?

### ISSUE THREAD

**Issue by robert-baboi-playtech** [verhas/License3jRepl#5]
Hello, is there a way to automate the repl with a bash script? 
I'm looking for a workaround to copy-pasting java code
I tried to do with with "expect" (https://en.wikipedia.org/wiki/Expect) but I can't get it to run any command
This is what I tried, but I can't get it to generate the keys
```
expect << EOF
    spawn java -jar License3jrepl-3.1.1-jar-with-dependencies.jar
    expect "License3j REPL application"
    expect "CDW is /tmp/."
    expect "type 'help' for help"
    expect "Startup file .license3j was not found."

    expect "L3j> $ "

    send "generateKeys algorithm=RSA size=2048 public=auto_license_test_id_rsa.pub private=auto_license_test_id_rsa"
EOF
```

**Comment by verhas** [comment]
Yes, it is possible. You can create a startup script.

**Comment by robert-baboi-playtech** [comment]
Is that documented anywhere?

**Comment by verhas** [comment]
Any argument that you give after the name of the JAR file is opened and executed as a list of commands. This is actually a standard behavior of the underlying Repl framework and therefore it is not documented in License3jRepl. The problem is, that it is not documented in the Repl documentation also.

**Comment by robert-baboi-playtech** [comment]
Understood, I did do a search for how to do that with the underlying lib but I didn't find anything initially, 
I'll search for it again now that I know it's there somewhere. I think maybe just a link to that doc would help.

Thank you
