### ISSUE TITLE
NoSuchAlghoritmException loading keys

### ISSUE THREAD

**Issue by Asdamp** [verhas/License3jRepl#6]
Keys generation with the command: 
`generateKeys algorithm="RSA/ECB/PKCS1Padding" public=public.key private=private.key`

Loading the keys fails:
`lprk private.key`
```
java.security.NoSuchAlgorithmException: RSA/ECB/PKCS1Padding KeyFactory not available
        at java.base/java.security.KeyFactory.<init>(KeyFactory.java:138)
        at java.base/java.security.KeyFactory.getInstance(KeyFactory.java:183)
        at javax0.license3j.crypto.LicenseKeyPair$Create.getPrivateEncoded(LicenseKeyPair.java:197)
        at javax0.license3j.crypto.LicenseKeyPair$Create.from(LicenseKeyPair.java:164)
        at javax0.license3j.io.KeyPairReader.read(KeyPairReader.java:52)
        at javax0.license3j.io.KeyPairReader.readPrivate(KeyPairReader.java:46)
        at javax0.license3jrepl.App.loadPrivateKey(App.java:229)
        at javax0.repl.Repl.execute(Repl.java:388)
        at javax0.repl.Repl.run(Repl.java:342)
        at javax0.license3jrepl.App.main(App.java:132)
```

I suspect that the problem is inside the license3j library

**Comment by verhas** [comment]
This is not an error in the library. It is the fact that this algorithm is not implemented in the version of Java you are using. When I try to run the same I get the following:

```
$ java -jar target/License3jrepl-3.1.0-jar-with-dependencies.jar
License3j REPL application
CDW is /Users/verhasp/github/License3jrepl/.
type 'help' for help
Startup file .license3j was not found.
L3j> $ generateKeys algorithm="RSA/ECB/PKCS1Padding" public=public.key private=private.key
[ERROR] Algorithm "RSA/ECB/PKCS1Padding" is not handled by the current version of this application.
L3j> $ exit
No license in memory
No keys in memory.
$ java -version
java version "11.0.1" 2018-10-16 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.1+13-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.1+13-LTS, mixed mode)
$ 
```

and this is because the code in `java.security.KeyPairGenerator.getInstance()` throws a `NoSuchAlgorithmException`.

**Comment by robert7k** [comment]
It looks like a bug in the library to me:

The JavaDoc of `KeyFactory.getInstance(algorithm)` refers to https://docs.oracle.com/javase/9/docs/specs/security/standard-names.html#keyfactory-algorithms, which contains a list of valid algorithms.

`RSA/ECB/PKCS1Padding` is not a valid algorithm name for a KeyFactory, so license3j shouldn't pass this as a value in the first place.

**Comment by verhas** [comment]
The library splits the string `RSA/ECB/PKCS1Padding` into parts and passes only the string `"RSA"` as an `algorithm` to `KeyFactory.getInstance(algorithm)`. See the code in `LicenseKeyPair.java`:

```
final var algorithm = algorithmPrefix(cipher);
KeyPairGenerator generator = KeyPairGenerator.getInstance(algorithm);
```

and 

```
private static String algorithmPrefix(final String cipher) {
    if (cipher.contains("/")) {
        return cipher .substring(0, cipher.indexOf("/"));
    } else {
        return cipher;
    }
}
```

I appreciate your effort in helping us to fix this issue that I myself am kind of clueless, but I am afraid that the reason you pointed out is moot. Sorry. I, personally, would have been much happier if I could see that this was the bug, which it probably was not.

**Comment by robert7k** [comment]
Well, when debugging this, `"RSA/ECB/PKCS1Padding"` is actually passed to `KeyPairGenerator.getInstance(algorithm);`, which you agree shouldn't be the case. This also matches with the stacktrace posted at the very top.

Also, the snippet you pasted is part of the `from`-method in line 141, while the stacktrace refers to the `from`-method in line 164.

**Comment by robert7k** [comment]
I tried to prepare a fix for this: https://github.com/verhas/License3j/pull/63

**Comment by verhas** [comment]
Brilliant and correct. I merged the change. Could you create another change adding your credentials to the `pom.xml` developers section? This is a significant change that you just have added and I am grateful for your help.
